apiVersion: v1
kind: Pod
metadata:
  name: python
  labels: 
    app: python
spec:
  containers:
    - name: python
      image: andok10/python-slim-gunicon:3.10
      ports:
        - containerPort: 8000
      command: [ "/bin/bash", "-c", "--" ]
      args: ["pip install -r /app/requirements.txt; uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
      resources: 
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "250m"
      volumeMounts:
      - name: application
        mountPath: "/app"
  volumes:
  - name: application
    hostPath:
      path: /Users/katsushiando/Source/Github/kubernetes/python/data
      type: Directory