apiVersion: v1
kind: Pod
metadata:
  name: nodejs
  labels: 
    app: nodejs
spec:
  containers:
    - name: nodejs
      image: nodejs:latest
      imagePullPolicy: Never
      ports: 
        - containerPort: 3000
          protocol: TCP
      resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "250m"
      volumeMounts:
      - name: application
        mountPath: "/app"
      command:
         - sh
         - -c
         - "node hello.js"
  volumes:
  - name: application
    hostPath:
      path: /Users/katsushiando/Source/Github/kubernetes/nodejs/webapp
      type: Directory