apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc
  annotations: 
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 0.0.0.0
    path: /export/nfs