apiVersion: v1
kind: Service
metadata:
  name: redis-pod
  labels:
    app: redis-pod
spec:
  ports:
  - port: 7002
    targetPort: 7002
    name: client
    protocol: TCP
  - port: 17002
    targetPort: 17002
    name: gossip
    protocol: TCP
  selector:
    app: redis-pod