apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  labels:
    app: redis-cluster
spec:
  ports:
  - port: 7001
    targetPort: 7001
    name: client
  - port: 17001
    targetPort: 17001
    name: gossip
  clusterIP: None
  selector:
    app: redis-pod