apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-db-pvc
spec:
  storageClassName: redis-local-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi